version: "3"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 123
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 15672:15672
      - 5672:5672
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"



